---
title: "Conclusions"
---

The availability of consistent monitoring data at multiple scales is an important challenge for avian conservation (Ruth et al., 2003). The IMBCR program meets this challenge through its probabilistic, nested design, which allows for inference to multiple scales of interest, from National Grasslands to states to BCRs (Pavlacky et al., 2017). With this design, we can model habitat relationships to evaluate species’ responses to local management actions and predict species’ distributions for landscape prioritization. Stratification based on eco-regional boundaries and other fixed attributes is also a critical feature of the IMBCR program because it allows for the evaluation of long-term avian responses to landscape and climate change (Metzger et al., 2013; Pavlacky et al., 2017).


The importance of long-term population monitoring at larger spatial scales is well known (Jones, 2011; Thompson et al., 1998), but it is often cost-prohibitive. The IMBCR program reduces expenses through cooperation with multiple partners, one of the stated goals of effective collaboration and coordinated bird monitoring (NABCI Monitoring Subcommittee, 2007), and also through efficiencies in data collection and analyses. Partners can investigate priority species and management questions with slight modifications to the IMBCR design, further reducing costs associated with developing new studies and monitoring programs. These cost savings allow for an increased sampling effort and/or for the development of decision support tools to aid land managers and conservation practitioners on the ground. Based on the spatially balanced design, the IMBCR program can also accommodate a shortage of monitoring funds in certain years or strata without reducing the overall rigor of the program (Stevens Jr. & Olsen, 2004).


The IMBCR program is well-positioned to address the conservation and management needs of a wide range of stakeholders due to its rigorous, hierarchical design and the strength of the IMBCR partnership. This partnership is an ongoing collaboration between multiple entities from state and federal agencies to non-governmental organizations and Joint Ventures, and was created to address management and conservation objectives of larger avian programs like NABCI (NABCI Monitoring Subcommittee, 2007). Through the IMBCR partnership, monitoring resources are pooled, creating efficiencies and allowing for inference to larger landscapes (Pavlacky et al., 2017). By providing essential knowledge of bird populations at multiple scales relevant to management and conservation, the IMBCR program informs prioritization of management actions and facilitates a collaborative approach to bird conservation (Ruth et al., 2003, Pavlacky et al., 2017).

