---
title: "Rocky Mountain Avian Data Center Tips"
editor: visual
---

## Overview

All results, including parameter estimates, distribution maps, raw count data and effort, are available online. To view interactive maps showing survey and detection locations, as well as species counts, and density, population and occupancy results using the IMBCR study design please visit the Rocky Mountain Avian Data Center. Click on the “Explore the Data” tab to view IMBCR results.

The Rocky Mountain Avian Data Center has been designed to provide information for specific questions and therefore works best when users select multiple filters for a query. To run a query, click the arrow for the drop down “Filter” menu (located in the extreme upper left corner of the screen) and select one of the following filter types: Study Design, BCR, State, County, Management Entity, Priority Species List, Species, Year, Superstratum, or Individual Stratum. After selecting the filter type, click the “Add” button immediately to the right of the drop down menu. A box will appear with options for the filter that you may select. Use the drop down menu in the box to select the specific filter and then click “Add filter”. The selected filter will appear near the top of the screen. Users may add multiple filter types to view results for a very specific inquiry (e.g., to view IMBCR results for BRSP in CO you would apply the following filters: Study Design = IMBCR, Species = Brewer’s Sparrow and State = CO) or to view multiple outputs at once (e.g., to view data and results for Brewer’s Sparrow and Vesper Sparrow at the same time select Species = Brewer’s Sparrow and Species = Vesper Sparrow). Below is an explanation of the different filter types you may choose from.

**Study Design**: This filter will allow users to select data and results for IMBCR, GRTS, Migration Phenology, NEON, or NPS study designs.

•	Selecting the GRTS filter will display data and results for monitoring efforts which used the IMBCR design but do NOT contribute to statewide and regional estimates (also known as “overlays”).


•	The IMBCR filter will select data and results collected under the IMBCR protocol that contribute to state and BCR-wide estimates. 


•	The Migration Phenology filter will select data and results for the Migration Phenology project.


•	The NEON study design is a specific study design developed by NEON and Bird Conservancy for surveys conducted at NEON research locations.


•	The NPS study designs are a mixture of study designs specifically designed for individual national parks. Please note that we are still working on adding some of the historic data to the Avian Data Center so not all study designs are currently available.


**BCR**: This filter will allow users to select data and results for a particular Bird Conservation Region. Selecting this filter will provide you with results for all strata and superstrata within a particular BCR.

**State**: This filter will allow users to select data and results for all study designs for a particular state. Selecting this filter will supply the user with data and results for all strata and superstrata within a particular state.

**County**: This filter will allow users to select data for a particular county. Please note that only raw count data and survey locations are available at the county level.

**Management Entity**: This filter will allow users to select data and results for All Other Lands, Colorado State Land Board, The Nature Conservancy (TNC), US Bureau of Indian Affairs (BIA), US Bureau of Land Management (BLM), US Department of Defense (DOD), US Fish and Wildlife Service (USFWS), US Forest Service (USFS), or National Park Service (NPS). Once a management entity is chosen, users may notice that additional filter types are available in the filters drop down list. These additional filter types, listed from most general to most specific, are management regions (e.g., USFS Region 1), management units (e.g., Dakota Prairie Grasslands), management forests (e.g., Shoshone National Forest), or management districts (e.g., North Kaibab district within Kaibab National Forest). Below is the filter hierarchy for the different management entities.

**Priority Species List**: This filter will allow users to select data and results for multiple species at once. The query will display data and results for all species included on the selected management indicator list, species of conservation concern list, etc.

**Species**: This filter allows users to select data and results for a particular species. 

**Year**: This filter will allow users to select all data and results for a particular year.

**Superstratum**: This filter allows users to select IMBCR data and results for multiple strata that were analyzed jointly (e.g., the entire Bridger-Teton National Forest which was broken up into 2 strata or the entire state of Colorado which was broken up into 30 strata). 

**Hierarchy for the different management entities**

**All Other Lands:**

Tier One – Management Entity – All Other Lands
Tier Two – Management Region – Not applicable
Tier Three – Management Unit – Not applicable
Tier Four – National Forest or Grassland – Not applicable
Tier Five – Management District – Not applicable

**Colorado State Land Board:**

Tier One – Management Entity – Colorado State Land Board
Tier Two – Management Region – Lowry Range
Tier Three – Management Unit – Not applicable
Tier Four – National Forest or Grassland – Not applicable
Tier Five – Management District – Not applicable

**TNC:**

Tier One – Management Entity – The Nature Conservancy
Tier Two – Management Region – Cherry Creek
Tier Three – Management Unit – Not applicable
Tier Four – National Forest or Grassland – Not applicable
Tier Five – Management District – Not applicable

**Tribal Lands:**

Tier One – Management Entity – US Bureau of Indian Affairs
Tier Two – Management Region – Reservation
Tier Three – Management Unit – Not applicable
Tier Four – National Forest or Grassland – Not applicable
Tier Five – Management District – Not applicable

**BLM:**

Tier One – Management Entity – Bureau of Land Management
Tier Two – Management Region – BLM Field Office
Tier Three – Management Unit – Not applicable
Tier Four – National Forest or Grassland – Not applicable
Tier Five – Management District – Not applicable

**DOD:**

Tier One – Management Entity – US Department of Defense
Tier Two – Management Region – US DoD Installation
Tier Three – Management Unit – Not applicable
Tier Four – National Forest or Grassland – Not applicable
Tier Five – Management District – Not applicable

**USFWS:**

Tier One – Management Entity – US Fish and Wildlife Service
Tier Two – Management Region – USFWS Region
Tier Three – Management Unit – USFWS Management Unit, Refuge, etc.
Tier Four – National Forest or Grassland – Not applicable
Tier Five – Management District – Not applicable

**USFS:**

Tier One – Management Entity – US Forest Service
Tier Two – Management Region – USFS Regions 
Tier Three – Management Unit – National Forest (NF) or National Grassland (NG) management units (used to represent situations where multiple forests are managed jointly)
Tier Four – National Forest or Grassland – NF or NG 
Tier Five – Management District – NF or NG Ranger Districts


**NPS:**

Tier One – Management Entity – National Park Service
Tier Two – Management Region – Inventory and Monitoring Network
Tier Three – Management Unit – Individual NPS Parks, Monuments, Memorials, Recreation Areas, and Historic Sites
Tier Four – Management Forest – Not applicable
Tier Five – Management District – Not applicable

**_Clearing Filters_**

Filters can be cleared in one of two ways. You may click on the circled “X” to the left of an individual filter at the top of the screen to remove it or you may click the “clear all filters” button at the top of the screen to start building a new query.

**_Running Queries_**

Once you have selected your desired filters, please click on the “Run Query” button located at the top of the screen. The amount of time it takes for the desired data and results to be displayed will depend on how specific your query is.

**_Comparing Multiple Queries_**

Users may view results of multiple queries at once. To do this, run the first query as described above and then click the button “New Query Window” (located at the top of the screen). A new window will appear where a separate query can be run. The two windows can then be viewed side by side.

**_Share a Created Query with a Colleague_**

It is possible to create a link to the Avian Data Center/ Explore the Data screen with a pre-loaded set of filters for a query. To do this, add the custom set of filters for your query per the instructions above and then click the “Generate URL” button near the top right corner of the screen. A pop-up box will appear with a highlighted URL address. Once you copy the highlighted text, you may paste the URL address into an email or document using conventional means. Please note that whoever receives the URL address will need to run the query after clicking on the link to see the survey locations, results, and raw count statistics for the set of filters of interest.

##Viewing Maps (Map Tab)

**_What is displayed_**

By default, the map tab is the initial start-up page. After clicking the “Run Query” button, the ADC will display a map of all survey locations corresponding to your set of filters (surveyed sampling units are represented by blue semi-transparent circles) using Google Maps. If you have filtered by species, blue circles represent survey locations where that species was not detected and blue circles with a pink dot in the center represent survey locations where that species was detected. To see the specific name of a survey location, hover the mouse arrow over the blue circle. After a moment the name of the surveyed sampling unit will appear. You may view the bird detection information for a sampling unit and the survey dates by left clicking your mouse on the blue circle.

By default, the zoom capability of the maps page is restricted to protect the privacy of private landowners. Funding and/or implementation partners wishing for more precise location information to be displayed should request a password from Bird Conservancy IT staff via email. Once a user has a password, click on the “View Options” button at the top of the screen, enter the password in the “Password for Bird Conservancy staff and partners” field, and click “Save”. If you have run a query prior to entering the password, you will need to click the “Run Query” button again in order to utilize the enhanced zooming features now available to you.

**_Adding map layers_**

You may add the following layers to the map: Bird Conservation Region boundaries, BIA boundaries, DoD boundaries, NPS boundaries, USFS boundaries and BLM Field Office boundaries. To do this, left click on the drop down menu at the top left corner of the map, select the desired layer, and click the “add layer” button. It is possible to add multiple layers to the map by repeating this process. The top-most feature’s name will appear if you left click your mouse inside the layer’s boundaries.

##Viewing Occupancy/Density Results (Occupancy and Density Tabs)

**_Viewing Tables_**

You may view occupancy or density results table and a chart for all appropriate strata (based on the set of filters) for which we have results, by clicking on the tabs labeled “Occupancy” or “Density”. These tabs are located just below the drop down filter menu in the upper left corner of the screen. The occupancy tables display species, stratum, year, Psi (proportion of sampling units expected to be occupied), number of sampling units the species was detected on, standard error (SE) of the estimate, the percent coefficient of variation (% CV). The density tables will display species, stratum, year, number of birds estimated per km² (D), total number of individuals estimated within the stratum (N), percent coefficient of variation (% CV), and the number of independent detections used in analyses (n). You may view a description of the column headings by moving the cursor over the column heading.

**_Viewing the Charts_**

When viewing the occupancy and density charts, the point estimate of Psi or D is indicated with a dot. Additionally, short horizontal dashes above and below the point estimate represent values one standard error away from the point estimate. To view the species, stratum and year that correspond to an estimate on the chart, simply move your mouse arrow over the point estimate or standard error bar. A message will pop up with the appropriate information. If you have queried out multiple years of data, the point estimates for each year will be connected with a solid line. You may remove an individual estimate from the chart by clicking on the corresponding row of the table on the left side of the screen. Estimates that are not displayed on the chart will turn a peach color in the table. You may add the estimate back onto the chart by clicking on the peach colored row in the table.

**_Knowing which species have estimates_**

To restrict the species filter to display only those species for which occupancy and/or density estimates have been produced, click on the “View Options” button on the very top of the screen and then check the box next to “Only show species for which occupancy/density results are available”. This will prevent you from querying out numerous species for which occupancy or density estimates are not available.

**_Saving results of your query_**

You may easily save the results of your query by clicking the “Copy to clipboard” button and pasting the results into another program such as excel or by clicking the “Save to CSV” button. Similarly, to save a chart click on the “View Image” button below the chart, right click on anywhere on the image and select “Copy image” or “Save image as”.

**_Functionality_**

Please keep in mind that queries with very generic filters will result in long wait times and may not function optimally (your browser may end up crashing). For instance, if a user selects only the IMBCR filter, occupancy results will be displayed for every species and strata/superstrata combination for which there are occupancy and/or density results. If your query is not specific enough, the chart on the right side of the screen will not be displayed or a pop-up box will appear asking if you would like to continue. This pop-up box is designed to prevent your web browser from crashing while the RMADC attempts to create a chart that would be extremely difficult to interpret. We recommend that you cancel the proposed query and add additional filters to make your query less generic. 

##Viewing Raw Count Statistics (Species Counts Tab)

You may view the raw count of detections for each species and the effort (expressed as the number of point count stations surveyed) for your query by clicking on the “Species Counts” tab located just below the drop down filter menu in the upper left corner of the screen. Both the counts (left table) and effort tables (right table) may be sorted by clicking on the row header. Additionally, you may view the counts and effort by BCR, State, County, Stratum, or Management Entity by clicking on the “Count by” drop down menu located above the counts table. If you have filtered using “Superstrata”, viewing counts by Stratum is an excellent way of getting a list of all the strata that comprise a Superstratum. If you would prefer to view effort expressed as the number of sampling units surveyed, click on the “View Options” button located at the top of the screen and check the box labeled “Show effort by number of sampling units instead of by point”.




