---
title: "IMBCR Program and Stratification History"
---

In 1995, Bird Conservancy of the Rockies (Bird Conservancy; formerly Rocky Mountain Bird Observatory), in partnership with Colorado Parks and Wildlife (CPW; formerly Colorado Division of Wildlife), the United States Forest Service (USFS), the Bureau of Land Management (BLM) and the National Park Service (NPS), began efforts to create and conduct a Colorado-wide program to monitor breeding bird populations. This was the first attempt in the nation to develop and implement a statewide landbird monitoring program. After a successful pilot year in 1998, Bird Conservancy implemented the protocol in 13 habitats in Colorado in 1999. Bird Conservancy and its partners used this methodology for 10 years and expanded the effort to include parts of Arizona, New Mexico, North Dakota, South Dakota, Utah, and Wyoming.

In 2007, the NABCI Monitoring Subcommittee published "Opportunities for Improving Avian Monitoring" (NABCI Monitoring Subcommittee, 2007) which offered recommendations for improving the efficiency and effectiveness of avian monitoring in North America. After taking NABCI's recommendations into consideration, IMBCR partners developed a new study design and protocol for statewide bird monitoring in Colorado. The new study design used BCRs as the sampling frame and further stratified by land ownership within each BCR.

## **2008** {.unnumbered}
IMBCR partners stratified and surveyed the Southern Rockies/Colorado Plateau BCR (BCR 16) and the Shortgrass Prairie BCR (BCR 18) portions of Colorado, as well as the BCR 16 portion of Wyoming. Furthermore, in Colorado BCR 16, we used cell weighting to target high order rivers and streams (based on Strahler stream order) and higher elevation habitats (e.g. alpine tundra), which occur in a small proportion of the landscape (Blakesley & Hanni, 2009).

## **2009**  {.unnumbered}
After the 2008 season, IMBCR partners determined the cell weighting had caused middle-elevations in Colorado to be under-sampled. To correct this, all strata in the Colorado and Wyoming portions of BCR 16 were re-stratified without cell weighting. Additionally, the All Other Lands stratum in Wyoming BCR 16 was split into two strata: All Other Lands and BLM Lands.

Based on the overall success of the pilot implementation, IMBCR expanded to include the Colorado and Wyoming portions of the Northern Rockies (BCR 10); the Great Basin (BCR 9) and BCR 18 portions of Wyoming; all of the Badlands and Prairies (BCR 17); the USFS National Forests and Grasslands within BCR 18; and Coconino and Prescott National Forests in the Sierra Madre Occidental (BCR 34).

## **2010**  {.unnumbered}
The program expanded to include the BCR 10 and the Prairie Potholes BCR (BCR 11) portions of Montana, three national forests in the Idaho portion of BCR 10 and Kaibab National Forest in BCRs 16 and 34. Additionally, there were several re-stratifications done in Colorado BCRs 10 and 16 between 2009 and 2010. The Colorado BCR 10 stratum was re-stratified to include the small easternmost portion of BCR 10 that dips into Colorado so all Colorado BCR 10 lands are represented. The "NPS Rocky Mountain Inventory and Monitoring Network (RMNW)" and "Northern Colorado Plateau Inventory and Monitoring Network (NCPN)" were re-stratified because some NCPN park units were initially misclassified into the RMNW stratum. In Wyoming, the USFS Region 4 stratum was re-stratified into three separate strata: "Bridger-Teton National Forest front-country/managed areas", "Bridger-Teton National Forest designated roadless/wilderness areas" and "the remainder of USFS Region 4 lands in Wyoming BCR 10". This re-stratification was done to allow for density and occupancy estimation specifically for the Bridger-Teton National Forest.

## **2011**  {.unnumbered}
The geographic extent of the IMBCR program expanded to the Nebraska portion of the Central Mixed Grass Prairie (BCR 19) and included all of the national forests and grasslands in Nebraska. Additionally, there were several re-stratifications done in Colorado. The Colorado BCR 10 stratum was split into two strata: BLM Lands and All Other Lands. This was done to facilitate improved tracking of priority species on BLM lands throughout Colorado. Rio Grande National Forest and White River National Forest strata were each split into three strata: low, medium, and high elevations. This stratification by elevation allowed sampling intensity changes to target Management Indicator Species on the forests. The Routt National Forest and Arapaho and Roosevelt National Forests strata were reorganized and a third stratum, the Williams Fork Area, was created from the two because it had mixed administration between the Routt National Forest and the Arapahoe and Roosevelt National Forests.

The RMNW stratum was re-stratified to accurately reflect land ownership. There was a land acquisition within Great Sand Dunes National Monument and some samples were removed from Rio Grande National Forest and added to the RMNW stratum; 16 km² were added to the area of the RMNW strata. In South Dakota, the Black Hills National Forest stratum was split into two strata based on watersheds in the Forest: Hydrologic Code 7 Watersheds and all other watersheds. Stratification by watershed allows for adjusting sampling intensity to target Management Indicator Species on the Forest.

## **2012**  {.unnumbered}
In 2012, we added four strata in Idaho to account for all of BCR10 within the state. We took into account the boundary between USFS Regions 1 and 4, which runs through Idaho, when stratifying so estimates could be generated at the USFS Region level. The new strata include "All Other Lands in the Region 1 portion of Idaho BCR 10" (all lands outside of national forest boundaries), "All Other Lands in the Region 4 portion of Idaho BCR 10" (all lands outside of national forest boundaries), "other USFS lands in the Region 1 portion of Idaho BCR 10" and "USFS designated roadless/wilderness areas within the Region 4 portion of Idaho BCR 10". In Arizona, Tonto National Forest became a part of the IMBCR survey effort. The forest was stratified into two strata based on elevation to allow sampling intensity changes to target Management Indicator Species on the Forests. Kaibab National Forest was re-stratified into two strata based on elevation for the same reason. In Montana, several strata were re-stratified and combined within BCR 17. The three "All Other Lands" strata were combined with the "Tribal Lands" stratum into one "All Other Lands" stratum. The four BLM strata within Montana BCR 17 were combined into one BLM stratum. These strata were collapsed into larger strata to maximize the number of samples conducted within two strata rather than spread them out amongst eight strata.

## **2013**  {.unnumbered} 
2013 brought significant changes to the program's overall stratification methods. The original IMBCR sampling grids were created at the state scale and as the program expanded, additional sampling grids were created at the BCR scale. In response to a rapidly growing monitoring program, the partnership acknowledged the need for a standard national grid system to promote the coordination and application of monitoring data in conservation. The group proposed the use of the United States National Grid (USNG), a national grid system created by the Federal Geographic Data Committee, as its standard. There are three advantages to using the USNG. First, the use of standard grids allows for the integration of datasets and subsequent identification of areas where sampling should or has not occurred. Second, it provides a means to identify sampled areas in a consistent manner so results of monitoring projects can be evaluated in a spatially comparable way. Lastly, it facilitates regional and national-level avian distribution modeling and the development of broad-scale avian distribution maps. This standard was approved by the NABCI committee. Bird Conservancy started using the USNG for new stratification and re-stratification schemes in 2013.

We added several USFS strata to the sampling frame for the 2013 field season -- Coronado National Forest in southern Arizona, Carson National Forest in north-central New Mexico, and Caribou-Targhee National Forest in southeastern Idaho. Coronado and Carson National Forests were stratified into two strata based on elevation to allow for adjusting sampling intensity to target Management Indicator Species on the Forests. Because Caribou-Targhee National Forest spans three states and three BCRs, it was necessary to divide the forest into four strata. The state and BCR-level stratification distinctions allowed the summation of the data for individual states or BCRs. The four new strata in Idaho and Utah join a preexisting Caribou-Targhee stratum in west-central Wyoming as a part of Wyoming's statewide effort. In addition, Pawnee National Grassland was split into two strata -- public lands and private lands -- since Pawnee National Grassland contains a large amount of private land within its administrative boundary. This allowed the USFS to concentrate more survey effort specifically on public lands. In Wyoming, the preexisting stratum in BCR 10 containing all USFS Region 4 lands (other than Bridger-Teton National Forest) was re-stratified into three separate strata, one for each Forest (Caribou-Targhee, Ashley, and Wasatch). This allows for forest-wide estimates within Caribou-Targhee National Forest. If, in the future, Ashley and Wasatch National Forests are completely sampled, this will also allow for forest-wide estimates in each of those forests.

The North Dakota, South Dakota, and Nebraska portions of BCR 17 underwent a complete re-stratification to incorporate several NPS Northern Great Plains Inventory and Monitoring Network (NGPN) strata. All of the non-NPS strata in these states were retained, but renamed to avoid confusion. The NPS strata were stratified by NPS unit to allow the NGPN to monitor birds on each of its units separately. New strata included Knife River Indian Villages National Historic Site, Theodore Roosevelt National Park, Badlands National Park, Jewel Cave National Monument, Mount Rushmore National Monument, and Wind Cave National Park.

Nebraska BCR 18 also underwent a complete re-stratification to allow for the individual stratification of Agate Fossil Beds and Scotts Bluff National Monuments. We also added an additional stratum for Cherry Ranch, a property owned by The Nature Conservancy (TNC).

## **2014**  {.unnumbered}
In Colorado, the Arapaho and Roosevelt and the Pike and San Isabel National Forests were re-stratified to allow these forests to monitor treatments intended to mitigate fire hazard and improve forest health. We divided each forest into two strata: a control stratum and the remainder of the forest. The control portion of the Arapaho and Roosevelt National Forests consists of lands ranging in elevation from 6,000 ft. (1,829 m) to 9,000 ft. (2,743 m) and excludes treatment areas and areas burned between 1998 and 2013. The Pike and San Isabel control stratum ranges from 6,000 ft. (1,829 m) to 9,500 ft. (2,896 m) and excludes treatment areas and areas burned between 1998 and 2013. We created a single experiment overlay stratum for all of Arapaho and Roosevelt and Pike and San Isabel National Forests consisting of actual treatment areas (areas with \>30% treatment). Since this stratum spans multiple forests, it is not considered to be a part of the IMBCR design; however, detections from this stratum do contribute to the number of detections used in analyses.

Significant stratification changes were made to the BCR 10 portion of Idaho. The four strata defined in the 2012 field season were further subdivided into nine strata. The boundary between USFS Regions 1 and 4 runs through Idaho and was taken into account when re-stratifying so that estimates could be generated at the USFS Region level. The new strata created in Idaho BCR 10 include the "Idaho portion of Bitterroot National Forest", "BLM Lands within Idaho BCR10", "Boise National Forest", "the Idaho portion of Kootenai National Forest", "Payette National Forest", "Salmon-Challis National Forest", "Sawtooth National Forest", "All other Lands within Idaho BCR 10 and USFS Region 1" (all lands outside of national forest and BLM boundaries) and "All Other Lands within Idaho BCR 10 and USFS Region 4" (all lands outside of national forest and BLM boundaries). Since Bitterroot and Kootenai National Forests span Idaho and Montana, 2014 density and occupancy estimates for those forests included strata from both states. In the past, "forest-wide" estimates have only represented the Montana portion of these forests.

We subdivided the US Fish and Wildlife Service (USFWS) strata in Montana BCRs 11 and 17 to allow density and occupancy estimation specifically within the Charles M. Russell National Wildlife Refuge. Previously, we grouped all USFWS lands together in these BCRs, limiting estimates for individual refuges. In each BCR, we created two new strata -- a Charles M. Russel NWR stratum and an "All Other USFWS Lands" stratum.

In addition to re-stratification, we added a few new strata to the IMBCR program in 2014. In Nebraska, NGPN began monitoring on the Niobrara National Scenic River spanning BCRs 17 and 19. In Utah, we created a new stratum for Manti-La Sal National Forest. Previously, only the Colorado portion of Manti-La Sal was stratified and surveyed. The additional Utah portion allows for the generation of forest-wide estimates for Manti-La Sal.

## **2015**  {.unnumbered}
In 2015, the Department of Defense (DoD) stratum in Colorado BCR 18 was completely re-stratified as part of a DoD Legacy Resource Management Program Grant to represent six individual military installations: US Air Force Academy, Fort Carson, Pueblo Chemical Depot, Piñon Canyon, and All Other DoD Lands. This DoD installation-level stratification allows for the generation of density and occupancy estimates for each installation. Fort Carson and Piñon Canyon were further stratified by areas within range fans (training zones) and areas outside of range fans to allow the DoD to assess the effects of military training on bird species.

The Rocky Mountain Arsenal National Wildlife Refuge stratum also came out of the 2015 re-stratification. During WWII, the Rocky Mountain Arsenal, as it was originally known, was a chemical weapons manufacturing facility. At the time of the 2008 IMBCR stratification in the state Colorado, it was still partially owned by the US Army and was included in the DoD stratum. The refuge is now in its own individual stratum.

The IMBCR program expanded to include the Missouri National Recreational River (MNRR), part of the NPS NGPN in Nebraska and South Dakota. There are two strata for MNRR representing the 39 Mile District and the 59 Mile District. In Utah, an additional stratum was added for Sanpitch Recreation Area. This area is part of Uinta National Forest but administered by Manti-La Sal National Forest and will be incorporated into forest-wide estimates for Manti-La Sal National.

## **2016**  {.unnumbered}
In 2016, the Playa Lakes Joint Venture (PLJV) coordinated a partnership between several state wildlife agencies and Bird Conservancy to expand sampling in five of the joint venture's six states: Nebraska, Kansas, New Mexico, Oklahoma, and Texas. PLJV's sixth state, Colorado, was already included in the IMBCR program starting in 2008. This expansion now provides the program with nearly complete coverage of two BCRs that were only sparsely covered in past years: Shortgrass Prairie (BCR 18) and Central Mixed Grass Prairie (BCR 19). The BCR 18 and 19 portions of these 5 states were divided into several strata, including, playas, rivers, biologically unique landscapes in Nebraska, and all other lands.

The IMBCR program also underwent a major expansion into the state of Utah in 2016. The entire state was stratified into BLM, USFS, DoD, and All Other Lands strata. This year was somewhat of a pilot year, with select BLM, USFS, DoD, and all other lands strata sampled across the state. In future years, sampling will be increased to a statewide level.

In addition to new strata, some existing strata were re-stratified for a variety of reasons. In North and South Dakota, we re-stratified the Tribal and All Other Lands strata to ensure all tribal lands were only included in the tribal lands strata. In the past, some tribal lands could still be found within the All Other Lands strata. We also re-stratified Cimarron, Kiowa, and Rita Blanca National Grasslands in Kansas, Oklahoma, New Mexico, and Texas. With the expansion of IMBCR throughout the PLJV region, these strata needed to be fit to the US National Grid to make them consistent with the rest of the IMBCR program in the region. In addition, we determined that the portion of Rita Blanca National Grassland that fell in New Mexico was actually managed by Kiowa National Grassland, so that portion was moved to the Kiowa National Grasslands stratum. All DoD lands in Colorado BCR18 were combined into one stratum. This was the same stratification used prior to 2015.

## **2017**  {.unnumbered}
In 2017, the IMBCR program expanded to include Humboldt-Toiyabe National Forest in two new states, Nevada and California. This, coupled with an expansion into national forests in Idaho BCR 9 and Utah yielded complete coverage of USFS lands at the regional level for USFS Region 4. Idaho also experienced a significant expansion with statewide coverage of BLM lands. In a concerted effort from several implementation partners, Utah sampling included statewide coverage, including several new BLM Field Offices, All Other Lands in BCR 10, and remaining Region 4 National Forests We also obtained complete coverage of BCR 18 for the first time by expanding into the BCR 18 portion of South Dakota.

USFWS strata in Montana BCR 11 and BCR 17 were re-combined in 2017 and reverted back to their pre-2014 areas. In Idaho, BLM Four Rivers Field Office in BCR 9 was split into two strata, incorporating the boundaries of Morley Nelson Snake River Birds of Prey National Conservation Area into the design. Additionally, we resampled All Other Lands in Nebraska BCR 17 to include eastern areas not included in the sampling frame from 2013-2016.

## **2018**  {.unnumbered}
In 2018, several Montana strata were combined to help produce statewide estimates. In BCR 10, the All Other Lands, Fish and Wildlife Service, National Park Service, Rivers, Blackfeet and Crow Reservations, and Flathead Reservation strata were combined into a single All Other Lands Stratum. In Montana BCR 11, we collapsed the Fish and Wildlife Service and Tribal Lands strata into a single Fish and Wildlife Service and Tribal Lands stratum. Two strata in Montana BCR 17, Fish and Wildlife Service and Rivers, were combined into a single Fish and Wildlife Service and Rivers stratum.

Additionally, Agate Fossil Beds National Monument and Scotts Bluff National Monument in Nebraska BCR 18 were combined into a single National Park Service Lands Stratum. In South Dakota BCR 17, the Badlands National Park - South Unit and Tribal Lands strata were combined into a single, new Tribal stratum, and Jewel Cave National Monument and Mount Rushmore were also collapsed into one National Park Service lands stratum.

Finally, Department of Defense strata in Utah were completely re-stratified to better assess the effects of military training on bird species.

## **2019**  {.unnumbered}
In 2019, the IMBCR program expanded to include all BLM lands in BCR 9 in California, Nevada, and Oregon. Great Basin Bird Observatory, Klamath Bird Observatory, and Point Blue conducted the field work in these new areas. This expansion improved coverage of sagebrush-steppe habitat.

The National parks strata in Nebraska and South Dakota that were collapsed in 2018 were separated into individual park units again in 2019 as they were in years previous to 2018. The individual park strata are Agate Fossil Beds National Monument and Scotts Bluff National Monument in Nebraska and Jewel Cave National Monument and Mount Rushmore in South Dakota.

## **2022**  {.unnumbered}
In 2020, several strata were combined in North Dakota and South Dakota to maintain BCR 17-wide estimates. In North Dakota, the Tribal Lands stratum and the All Other Lands stratum were collapsed into a single All Other Lands stratum. Similarly, in South Dakota, the Tribal Lands stratum and the All Other Lands stratum were collapsed into a single All Other Lands stratum.

In Nebraska, the BCR 18 All Other Lands stratum, Pineridge Biologically Unique Landscape stratum, Sandsage Prairie Biologically Unique Landscape stratum, and Wildcat Hills Biologically Unique Landscape stratum were combined into a single Nebraska BCR 18 All Other Lands stratum. We changed this stratification because those specific Biologically Unique Landscape strata were no longer of interest to the Nebraska partners.

## **2021**  {.unnumbered}
In 2021, IMBCR expanded to include BCR 10 BLM lands in the Burns, Prineville, and Vale Districts.

## **2022**  {.unnumbered} 
In 2022, we combined several strata within two National Forests in Colorado that had previously been created to serve as control strata for an overlay project. In Arapaho Roosevelt National Forest we combined the Arapaho Roosevelt National Forests All Other stratum (CO-BCR16-VO) and the Arapaho Roosevelt National Forests Control (CO-BCR16-RC) stratum into a single stratum for the forest (CO-BCR16-AR). In Pike-San Isabel National Forest we combined the Pike San Isabel National Forests All Other (CO-BCR16-PO) stratum and the Pike and San Isabel National Forests Control (CO-BCR16-PC) stratum into a single stratum for the forest (CO-BCR16-PS). In South Dakota, the Black Hills National Forest - Hydrologic Code 7 Watersheds (SD-BCR17-HU) stratum and the Black Hills National Forest - All other Watersheds (SD-BCR17-BF) stratum were combined into a single Black Hills National Forest stratum (SD-BCR17-BI). This change was made to help maintain survey coverage of the forest.
