---
title: "Protocol Changes Over Time"
editor: visual
---

The original protocol implemented in 2008 has changed and evolved over time to better facilitate analysis and meet partner needs. In 2009, observers began recording the primary habitat type at each sample point from a list of habitat options. We added categorical habitat options to facilitate data proofing, to incorporate habitat in analysis and to link the IMBCR data and results with the older habitat-based monitoring program. Observers also began recording the presence of water and snow within 50 m of each point as a type of ground cover.

Beginning in 2010, the point count duration was increased from five minutes to six minutes to facilitate occupancy estimation, which is easier to analyze using equal time intervals (in this case, two minutes each). Observers began recording juvenile birds detected during point counts. Observers placed a “J” in the sex column for these detections. Previously, juvenile birds were not recorded because this study focuses on recording breeding birds. Juvenile bird detections are used for distribution mapping purposes only and are not factored into data analysis. A minute column was added to the bird datasheet so observers could record the actual minute of each bird detection during a point count. Previously, observers used tick marks to separate minute intervals. We added a “visual” checkbox to the bird datasheet for observers to check if they visually observed and identified any of the species recorded. This reminds observers that they need to look for birds in addition to listening for them and helps crew leaders make decisions regarding unusual or rare bird detections while proofing data. We provided observers with an additional datasheet to record the reasons points were not surveyed (e.g., weather issues, unsafe terrain, denied permission by landowner, etc.). This sheet also provided space to record additional landowner information as needed. Lastly, observers began recording horizontal distance to each flyover detection. In the past, we did not record distances because we do not use flyover detections in analysis. However, observers sometimes incorrectly distinguish flyovers from birds using the surrounding habitat while foraging on the wing (e.g., swallows, swifts, and raptors). Therefore, if we find an incorrectly recorded flyover, we can still use the detection data in analysis.

In 2012, observers began recording the start time for every point count conducted so we could use temporal information as a variable in analyses. Start times for the entire transect and for individual points were all recorded in Mountain Daylight Time for consistency across the region. Prior to 2012, observers were allowed to conduct point counts until 11:00 AM local time each day. In order to account for variability across study areas from Arizona to Montana, crew leaders instructed observers to survey no later than five hours after sunrise in 2012. Observers also began noting migrant detections on surveys. After the field season, we thoroughly review the migrant records; if those records are verified, they are not included in analysis. Previously, crew leaders instructed observers to record a bird as a male if 1) it was a singing warbler or sparrow, or 2) it was singing repeatedly and emphatically. In 2012, we instructed observers to only identify the sex of a visually observed bird of a sexually dimorphic species. We instructed observers to record subspecies only if they visually identified a bird as such. In the past, we used geographic range to assume a bird was of a particular subspecies. Up until the 2012 field season, we provided observers with a list of rare or difficult to detect species to record while traveling between points within a sampling unit. In 2012, in order to simplify the protocol and collect more useful information, we eliminated the list and observers recorded any species they came across while traveling between points they had not documented during a point count. That way all species encountered within the sampling unit would be documented for distribution mapping purposes.

Also in 2012, several changes were made to the vegetation datasheet. First, we removed distance to the nearest road, forest structural stage and human structures from the data sheet. We no longer collect these types of data in the field because they can be obtained through remote sensing. Second, we modified the datasheet to simply record whether a mid-story was present. In the past, if mid-story vegetation was present, observers would record the species found in that layer. Data analysis found mid-story vegetation data to be extremely variable from year to year. Third, we added a ground cover category for residual grass. Finally, we limited acceptable overstory, understory, and ground cover relative abundance values to 1%, 5%, or increments of 10%. In the past, observers estimated cover to the nearest percent for all categories where percent cover or relative abundance was recorded. We made the change to improve the consistency of cover and relative abundance estimates and to decrease the amount of time observers spend estimating these values.

In 2012, crew leaders provided observers with two additional data sheets to facilitate working on private lands. The first contained specific information about the land ownership of each point located within a given sampling unit. In cases where a point fell on private property, the data sheet contained the name, contact information and any pertinent notes about the landowner. The second data sheet was a contact log where observers recorded all contacts or attempted contacts they had with landowners. This information was later entered into the landowner database when the observer had internet access.

In 2015, we began recording American pika, similarly to the way we record Abert’s and American red squirrels. In 2017, we added a checkbox onto the vegetation data sheet to mark the presence/absence of invasive cheatgrass.

In 2018, we made one change to the ground cover section of the vegetation protocol to collect more specific data on ground cover types. We split the bare/litter ground cover category into bare ground and litter cover so that future analyses could treat these categories separately. 



