project:
  type: book
  output-dir: docs

book:
  title: "Integrated Monitoring in Bird Conservation Regions"
  date: "3/20/2023"
  sidebar:
    title: "2022 IMBCR Field Season Report"
    logo: BCR-logo.png
    style: floating
    
  chapters:
    - index.qmd
    - 2-about-us.qmd
    - 3-exec-summary.qmd
    - 4-tables-figures.qmd
    - 5-intro.qmd
    - 6-methods.qmd
    - part: "Results"
      chapters: 
        - 7-results.qmd
        - 8-usfs.qmd
        - 9-blm.qmd
        - 10-dod.qmd
        - 11-nps.qmd
        - 12-tribal.qmd
        - 13-all-other.qmd
        - 14-bcr.qmd
        - 15-co.qmd
        - 16-mt.qmd
        - 17-ut.qmd
        - 18-wy.qmd
    - part: "Discussion"
      chapters:
        - 19-applications.qmd
        - 20-trends.qmd
        - 21-conclusion.qmd
    - 22-references.qmd
  appendices: 
    - 23-adc-tips.qmd
    - 24-history.qmd
    - 25-protocol-changes.qmd
    - 26-analysis.qmd
    - 27-priority-species.qmd
        

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc-title: "On this page"
    number-sections: true
    number-depth: 2
    fontsize: 1em
    prefer-html: true

editor: source

filters:
  - newpagelink.lua
