---
title: "Tables and Figures"
format: html
prefer-html: true
---

## Tables {.unnumbered}

<a href="#tbl-planned-completed">Table&nbsp;<span>1</span></a> Planned and completed surveys by strata, 2022.

<a href="#sec-reasons">Table&nbsp;<span>2</span></a> Reasons planned surveys were not completed, 2022.

<a href="#sec-table-3">Table&nbsp;<span>3</span></a> Population trend estimates for sensitive sagebrush bird species within select Wyoming Bureau of Land Management strata from the IMBCR program.

<a href="#sec-table-4">Table&nbsp;<span>4</span></a> Population trend estimates for two grassland bird species within Bird Conservation Region 17 from the IMBCR program.

<a href="#sec-table-5">Table&nbsp;<span>5</span></a> Population trend estimates for sensitive species within select U.S. Forest Service National Grassland and National Forest strata from the IMBCR program.

<a href="#sec-reasons">Table&nbsp;<span>2</span></a> Reasons planned surveys were not completed, 2022.

## Figures {.unnumbered}

::: {.callout-note}
Figure numbers begin with their respective chapter numbers.
:::

@fig-bcr-regions Bird Conservation Regions throughout North America, excluding Hawaii and Mexico.

@fig-extent Spatial extent of sampled Bird Conservation Regions using the IMBCR design, 2022.

@fig-sampling-unit Example 1 km² sampling unit in the IMBCR design.

@fig-bcr-17 Survey locations and strata in Bird Conservation Region 17, 2022

@fig-co Survey locations and strata in Colorado, 2022

@fig-mt Survey locations and strata in Montana, 2022.

@fig-ut Survey locations and strata in Utah, 2022.

@fig-wy Survey locations and strata in Wyoming, 2022.




